vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        formation_videos:
            uri_prefix: '%formation_videos%'
            upload_destination: '%kernel.project_dir%/public/%formation_videos%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
